apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appliance.apps.mumoshu.github.io
spec:
  group: apps.mumoshu.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    kind: Appliance
    plural: appliance
    singular: appliance
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            source:
              type: string
            values:
              type: object
            envvars:
              type: object
